version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "chore: "
      prefix: "chore"
    open-pull-requests-limit: 10
