name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - uses: pnpm/action-setup@v4
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: install test dependencies (1/2)
        run: cd tests/usage/import && pnpm install --frozen-lockfile
      - name: install test dependencies (2/2)
        run: cd tests/usage/require && pnpm install --frozen-lockfile
      - name: lint
        run: pnpm lint
  unit:
    strategy:
      matrix:
        node: ["22.x"]
        platform: [ubuntu-latest]
    name: Unit Tests (Node v${{matrix.node}} ${{matrix.platform}})
    runs-on: ${{matrix.platform}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
      - uses: pnpm/action-setup@v4
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: run tests (unit)
        run: pnpm run test
      - name: coverage
        uses: codecov/codecov-action@v4
        if: github.actor != 'dependabot[bot]'
        with:
          fail_ci_if_error: true
          verbose: false
          token: ${{ secrets.CODECOV_TOKEN }}
        env:
          CI: true
  integration:
    strategy:
      matrix:
        node: ["22.x"]
        platform: [ubuntu-latest]
    name: Integration Tests (Node v${{matrix.node}} ${{matrix.platform}})
    runs-on: ${{matrix.platform}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
      - uses: pnpm/action-setup@v4
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: run tests (integration)
        run: pnpm run test:integration
      - name: coverage
        uses: codecov/codecov-action@v4
        if: github.actor != 'dependabot[bot]'
        with:
          fail_ci_if_error: true
          verbose: false
          token: ${{ secrets.CODECOV_TOKEN }}
        env:
          CI: true

  usage-import:
    strategy:
      matrix:
        node: ["22.x"]
        platform: [ubuntu-latest]
    name: Usage Tests (Import) (Node v${{matrix.node}} ${{matrix.platform}})
    runs-on: ${{matrix.platform}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
      - uses: pnpm/action-setup@v4
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: build project
        run: pnpm build
      - name: run tests (usage:import)
        run: pnpm run test:usage:import

  usage-require:
    strategy:
      matrix:
        node: ["22.x"]
        platform: [ubuntu-latest]
    name: Usage Tests (Require) (Node v${{matrix.node}} ${{matrix.platform}})
    runs-on: ${{matrix.platform}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
      - uses: pnpm/action-setup@v4
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: build project
        run: pnpm build
      - name: run tests (usage:require)
        run: pnpm run test:usage:require

  release-preview:
    runs-on: ubuntu-latest
    needs: [lint, unit, integration]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - uses: pnpm/action-setup@v4
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: build project
        run: pnpm run build
      - name: release preview with pkr-pr-new
        run: pnpm exec pkg-pr-new publish
